---
- name: "ansible_facts_output_var"
  ansible.builtin.debug:
    var: ansible_facts_output_var

- name: "cloud_element in get_user_details_001"
  ansible.builtin.debug:
    var: cloud_element

- name: "Check Mandatory Variables are defined"
  ansible.builtin.assert:
    that: 
      - ansible_facts_output_var is defined
      - cloud_element is defined
    success_msg: All madatory variables for this role are defined
    fail_msg: Missing mandatory variable(s) to execute the role. 

- name: Assert mandatory variables are defined
  ansible.builtin.assert:
    that:
    - cloud_element.id is defined 
    # The object ID or principal name of the user for which to get information.
    success_msg: All mandatory variables for this role are present
    fail_msg: Missing mandatory variable(s) for this role

- name: Get user details {{ cloud_element.display_name }}
  ansible.builtin.command: >
    az ad user show \
    --id  {{ cloud_element.id }}
  register: userDetails

- name: Set result
  ansible.builtin.set_fact:
    cacheable: true
    "{{ ansible_facts_output_var | mandatory }}": "{{ userDetails }}"