---
- name: Print cloud_element
  ansible.builtin.debug:
    var: cloud_element

- name: "Check Mandatory Variables are defined"
  ansible.builtin.assert:
    that: 
      - ansible_facts_output_var is defined
      - cloud_element is defined
    success_msg: All madatory variables for this role are defined
    fail_msg: Missing mandatory variable(s) to execute the role. 


# - name: Print location
#   ansible.builtin.debug:
#     msg: location - {{ location }}
# - name: Print tags
#   ansible.builtin.debug:
#     msg: tags - {{ tags }}

- name: Assert mandatory variables are defined
  ansible.builtin.assert:
    that:
    - cloud_element.name is defined
    - cloud_element.group_name is defined
    - cloud_element.tags is defined
    - cloud_element.location is defined
    - cloud_element.sku_tier is defined
    success_msg: All mandatory variables for this role are present
    fail_msg: Missing mandatory variable(s) for this role

- name: Create Azure Container Registry
  ansible.builtin.command: >
    az acr create \
    --resource-group {{ cloud_element.group_name }} \
    --name {{ cloud_element.name }} \
    --sku {{ cloud_element.sku_tier }} \
    --location {{ cloud_element.location }} \
    --tags={{ local_tags.items() |map('join', '=') | map('regex_replace', '[ <>:\+_/;&"\?\\]', '_') |join(' ') }}
  register: acr_created

- name: Set result
  ansible.builtin.set_fact:
    cacheable: true
    "{{ ansible_facts_output_var | mandatory }}": "{{ acr_created }}"
