---
- name: Create Resource Group
  import_playbook: create-rg.yml

- name: Create VNET
  import_playbook: create-vnet.yml

- name: Create Subnets
  import_playbook: create-subnets.yml

- name: Create Log-Workspace
  import_playbook: create-log-worspace.yml

- name: Create Monitoring-Workspace
  import_playbook: create-monitor-workspace.yml
  when: Monitor_Workspace is defined and Monitor_Workspace == true

- name: Create Azure Kubernetes
  import_playbook: create-aks.yml