---

- name: Create Resource Group
  hosts: all 
  tasks:
    - name: Include Azure factory global main variables 
      include_vars: "{{ playbook_dir }}/../vars/global-main.yml"

    - name: Include Azure factory regional main variables 
      include_vars: "{{ playbook_dir }}/../vars/{{ stage }}/region-main.yml"

    - name: Print globalvariables
      ansible.builtin.debug:
        msg: globalvariables - {{ globalvariables }}
    - name: Print regionalVariables
      ansible.builtin.debug:
        msg: regionalVariables - {{ regionalVariables }}
    
    - name: Login to Azure
      ansible.builtin.import_role:
        name: login_azure_sp_cert_01
      vars: 
        spn_appID: "{{ identities.spn.app01.appid }}"
        tenant_id: "{{ globalvariables.tenant_id }}"
        certificate: "{{ identities.spn.app01.certificateName }}"
        certificatePath: "{{ playbook_dir }}/../certificate"

    - name: Create Vnet
      ansible.builtin.import_role:
        name: create_vnet_001
      vars:
        cloud_element:
          name: "{{ vnet.vnet_1.name }}"
          group_name: "{{ resourcegroup.resource_group_1.name }}"
          tags: "{{ regionalVariables.tags }}"
          settings: 
            address_prefixes: "{{ vnet.vnet_1.address_prefixes }}"
          location: "{{ regionalVariables.location }}"
        ansible_facts_output_var: "vnet_1_out"

    - name: ansible_facts.vnet_1_out
      ansible.builtin.debug:
        var: ansible_facts.vnet_1_out