# ------------------------------------------------------------------------------
# Owner: Alok Adhao
# Repository: https://github.com/Casa-Cloud
# Description: This file is part of the Casa-Cloud project ansible-azure
# Created: 2025-04-13
# License: MIT
# ------------------------------------------------------------------------------

---

- name: Delete Users
  hosts: all 
  connection: local
  tasks:
    - name: Include Azure factory global main variables 
      include_vars: "{{ playbook_dir }}/../vars/global-main.yml"

    - name: Include Azure factory regional main variables 
      include_vars: "{{ playbook_dir }}/../vars/{{ stage }}/region-main.yml"
    
    - name: Login to Azure
      ansible.builtin.import_role:
        name: casa_cloud.core.login_azure_sp_cert_01
      vars: 
        spn_appID: "{{ identities.spn.app01.appid }}"
        tenant_id: "{{ globalvariables.tenant_id }}"
        certificate: "{{ identities.spn.app01.certificateName }}"
        certificatePath: "{{ playbook_dir }}/../certificate"

    # this is looping through the users list in regin-main.yml
    - name: "Loop through users and delete assigned roles"
      ansible.builtin.include_tasks: ../tasks/rbac/delete-rbac_loop_users.yaml
      loop: "{{ users | dict2items }}"
      loop_control:
        loop_var: user_item

    # This loop is important and working. do not remove it.
    - name: "Loop through users and delete"
      ansible.builtin.include_tasks: ../tasks/delete-users_task.yaml
      loop: "{{ users | dict2items }}"
      loop_control:
        loop_var: item