# ------------------------------------------------------------------------------
# Owner: Alok Adhao
# Repository: https://github.com/Casa-Cloud
# Description: This file is part of the Casa-Cloud project ansible-azure
# Created: 2025-04-13
# License: MIT
# ------------------------------------------------------------------------------

---
- name: Print cloud_element
  ansible.builtin.debug:
    var: cloud_element

- name: "Check Mandatory Variables are defined"
  ansible.builtin.assert:
    that: 
      - ansible_facts_output_var is defined
      - cloud_element is defined
    success_msg: All madatory variables for this role are defined
    fail_msg: Missing mandatory variable(s) to execute the role. 


# - name: Print location
#   ansible.builtin.debug:
#     msg: location - {{ location }}
# - name: Print tags
#   ansible.builtin.debug:
#     msg: tags - {{ tags }}

- name: Assert mandatory variables are defined
  ansible.builtin.assert:
    that:
    - cloud_element.name is defined
    - cloud_element.group_name is defined
    success_msg: All mandatory variables for this role are present
    fail_msg: Missing mandatory variable(s) for this role

- name: Check Azure AKS access to ACR
  ansible.builtin.command: >
    az aks get-credentials \
    --resource-group {{ cloud_element.group_name }} \
    --name {{ cloud_element.name }} \
    --overwrite-existing
  register: aks_login_output


- name: aks_login_output
  ansible.builtin.debug:
    var: aks_login_output

- name: Failed AKS login
  fail:
    msg: "AKS login failed"
  when: aks_login_output.rc != 0

- name: Print success message
  debug:
    msg: "Git is installed on this system."
  when: aks_login_output.rc == 0

- name: kubelogin convert kubeconfig
  command: kubelogin convert-kubeconfig -l azurecli
  register: kubelogin_convert_out
  ignore_errors: true

- name: kubelogin_convert_out
  ansible.builtin.debug:
    var: kubelogin_convert_out

- name: Failed kubelogin convert kubeconfig
  fail:
    msg: "Failed kubelogin convert kubeconfig"
  when: kubelogin_convert_out.rc != 0

- name: Success kubelogin convert kubeconfig
  debug:
    msg: "Success kubelogin convert kubeconfig"
  when: kubelogin_convert_out.rc == 0

- name: Set result
  ansible.builtin.set_fact:
    cacheable: true
    "{{ ansible_facts_output_var | mandatory }}": "{{ kubelogin_convert_out }}"